spring:
  application:
    name: PostPrep


  ai:
    huggingface:
      api-key: ${HUGGINGFACE_API_KEY}
      chat:
        base-url: https://router.huggingface.co/v1
        options:
          model: Qwen/Qwen2.5-7B-Instruct
    embedding:
      transformer:
        onnx:
          model-uri: https://huggingface.co/Xenova/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx
          tokenizer-uri: https://huggingface.co/Xenova/all-MiniLM-L6-v2/resolve/main/tokenizer.json

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/postprep

    username: postgres
    password: 123
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


jwt:
    access-token-expiration-duration: 1h
    access-token-public-key: classpath:certs/public.pem
    refresh-token-expiration-duration: 7d
    access-token-private-key: classpath:certs/private.pem

