spring:
  application:
      name: PostPrep
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postprep
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
    access-token-expiration-duration: 1h
    access-token-public-key: classpath:certs/public.pem
    refresh-token-expiration-duration: 7d
    access-token-private-key: classpath:certs/private.pem

